DROP TABLE IF EXISTS links;

CREATE TABLE links (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    link_key TEXT NOT NULL,
    content TEXT NOT NULL
);